# Backend lint
# Backend test

# Docker login to ECR
# Docker build
# Docker push

# Frontend lint
# Frontend test

# Frontend deploy

# Backend deploy
#  - test backend
#  - build & push Docker image
#  - update aws lambda tag
#  - (maybe delete the old one?)

name: Build Backend
run-name: backend-build-${{ github.actor }}
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - 
        name: Build and push lambda
        run: |
          make build_and_push_docker_image region=$AWS_REGION account_id=${{secrets.ACCOUNT_ID}} name=tumpr-backend build_no=${{github.run_id}} aws_ecr_repository=${{secrets.account_id}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/tumpr-dev-image-repository


