# Backend lint
# Backend test

# Docker login to ECR
# Docker build
# Docker push

# Frontend lint
# Frontend test

# Frontend deploy

# Backend deploy
#  - test backend
#  - build & push Docker image
#  - update aws lambda tag
#  - (maybe delete the old one?)

name: Build Backend
run-name: backend-build-${{ github.actor }}
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{vars.AWS_REGION}}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - 
        name: Build and push Docker image
        run: |
          make build_and_push_docker_image \
            region=${{vars.AWS_REGION}} \
            account_id=${{secrets.ACCOUNT_ID}} \
            name=tumpr-backend build_no=${{github.run_id}} \
            ecr_url=${{secrets.account_id}}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com/tumpr-dev-image-repository
      - 
        name: Update Lambda function
        run: |
          make update_lambda_with_latest_image \
            function_name=tumpr-dev-backend-lambda \
            account_id=${{secrets.account_id}} \
            region=${{vars.AWS_REGION}} \
            ecr_name=tumpr-dev-image-repository


