env:
  APP_NAME: tumpr
  S3_BUCKET:

name: Build Frontend
run-name: frontend-build-${{ github.actor }}
on:
  pull_request:
    paths:
      - frontend/**
      - .github/**
jobs:
  Lint:
    runs-on:
      ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    -
      name: checkout
      uses: actions/checkout@v4
    -
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{vars.AWS_REGION}}
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    -
      name: Use Node.js 20.11.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.11.0
    -
      name: Install node dependencies
      uses: bahmutov/npm-install@v1
      with:
          working-directory: frontend
    -
      name: Lint
      run: |
        npm run format:check
        npm run lint:check
    -
     name: build
     run: |
        npm run build
    -
     name: deploy to S3
     run: |
        aws s3 sync dist s3://tumpr-staging-ui --delete
